apiVersion: v1
kind: Service

metadata:
  name: kafka
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: kafka

  ports:
  - port: {{ .Values.kafka.port }}
    targetPort: {{ .Values.kafka.port }}

  type: ClusterIP