apiVersion: v1
kind: Service

metadata:
  name: subscriber-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: subscriber-service

  type: {{ .Values.subscriber.service.type }}

  ports:
  - port: {{ .Values.subscriber.service.port }}
    targetPort: {{ .Values.subscriber.service.port }}
    nodePort: {{ .Values.subscriber.service.nodePort }}